# Generated by Django 4.2.6 on 2023-10-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type_animal', models.CharField(max_length=25)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='services.servicemodel')),
            ],
            options={
                'db_table': 'animal',
            },
        ),
    ]
